name: Show Push User Email

on:
  push:

jobs:
  show-email:
    runs-on: ubuntu-latest

    steps:
      - name: Show push user
        run: |
          echo "GitHub ID: ${{ github.actor }}"
          echo "Email: ${{ github.event.head_commit.author.email }}"
